spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
  datasource:
    username: root
    password: Asdf1234!
    url: jdbc:mariadb://localhost:3306/batch
    driver-class-name: org.mariadb.jdbc.Driver